In [20]:
# # Unit 3 | Assignment - Py Me Up, Charlie

# # PyBank - HW #1

# * In this challenge, you are tasked with creating a Python script for analyzing the financial records of your company. You will give a set of financial data called [budget_data.csv](PyBank/Resources/budget_data.csv). The dataset is composed of two columns: `Date` and `Profit/Losses`. (Thankfully, your company has rather lax standards for accounting so the records are simple.)

# * Your task is to create a Python script that analyzes the records to calculate each of the following:

#   * The total number of months included in the dataset

#   * The net total amount of "Profit/Losses" over the entire period

#   * The average of the changes in "Profit/Losses" over the entire period

#   * The greatest increase in profits (date and amount) over the entire period

#   * The greatest decrease in losses (date and amount) over the entire period

# * As an example, your analysis should look similar to the one below:

#   ```text
#   Financial Analysis
#   ----------------------------
#   Total Months: 86
#   Total: $38382578
#   Average  Change: $-2315.12
#   Greatest Increase in Profits: Feb-2012 ($1926159)
#   Greatest Decrease in Profits: Sep-2013 ($-2196167)
#   ```

# * In addition, your final script should both print the analysis to the terminal and export a text file with the results.

import csv

csv_path = (r"C:\Users\ryanz\Desktop\Data Analytics Bootcamp\Resources\RICH201901DATA3\03-Python\Homework\Instructions\PyBank\Resources\budget_data.csv")

myData = []

with open(csv_path, newline="") as csvfile:
    
    csvreader = csv.reader(csvfile, delimiter=',')
    
    csv_header = next(csvreader)
    myData.append(csv_header)
    
    for row in csvreader:
        myData.append(row)

# The total number of months included in the dataset
# The net total amount of "Profit/Losses" over the entire period

total_month = 0
total_pl = 0

for row in myData[1:]:
    total_month += 1
    total_pl += int(row[1])

print("Financial Analysis")
print("---------------------------")
print(f"Total Months: {total_month}")
print(f"Total ${total_pl}")
        
# The average of the changes in "Profit/Losses" over the entire period

cum_chg = 0

# Extract the P/L values by themselves
pl_list = [int(b) for a, b in myData[1:]]

# List Comprehension
# Zip the list to itself with an offset of 1 in order to get an offset list
# In doing so, you create 1 new value list by subtracting the second value in the list to the first value
valchg_list = [x - y for x , y in zip(pl_list[1:],pl_list)]

# Divide the sum of the value change list by the length of the value change list - the value chg list will give you 85
# Length of a list will count the number of iterations...where as length of a text item will give you length of the object
avgchg = sum(valchg_list)/len(valchg_list)

print(f"Average Change: ${round(avgchg, 2)}")

month_list = [i for i, j in myData[1:]]
month_chg_list = [i for i in zip(month_list[1:], valchg_list)]

# The greatest increase in profits (date and amount) over the entire period
# The greatest decrease in losses (date and amount) over the entire period
for row in month_chg_list:
    if row[1] == max(valchg_list):
        gr_incmonth = row[0]
        gr_incval = row[1]
    if row[1] == min(valchg_list):
        gr_decmonth = row[0]
        gr_decval = row[1]

    
print(f"Greatest Increase in Profits: {gr_incmonth} (${gr_incval})")
print(f"Greatest Decrease in Profits: {gr_decmonth} (${gr_decval})")

Financial Analysis
---------------------------
Total Months: 86
Total $38382578
Average Change: $-2315.12
Greatest Increase in Profits: Feb-12 ($1926159)
Greatest Decrease in Profits: Sep-13 ($-2196167)

In [23]:
# ## PyPoll - HW #2

# * In this challenge, you are tasked with helping a small, rural town modernize its vote-counting process. 
#   (Up until now, Uncle Cleetus had been trustfully tallying them one-by-one, but unfortunately, his concentration isn't 
#   what it used to be.)

# * You will be give a set of poll data called [election_data.csv](PyPoll/Resources/election_data.csv). The dataset is 
#   composed of three columns: `Voter ID`, `County`, and `Candidate`. Your task is to create a Python script that analyzes
#   the votes and calculates each of the following:

#   * The total number of votes cast

#   * A complete list of candidates who received votes

#   * The percentage of votes each candidate won

#   * The total number of votes each candidate won

#   * The winner of the election based on popular vote.

# * As an example, your analysis should look similar to the one below:

#   ```text
#   Election Results
#   -------------------------
#   Total Votes: 3521001
#   -------------------------
#   Khan: 63.000% (2218231)
#   Correy: 20.000% (704200)
#   Li: 14.000% (492940)
#   O'Tooley: 3.000% (105630)
#   -------------------------
#   Winner: Khan
#   -------------------------
#   ```

# * In addition, your final script should both print the analysis to the terminal and export a text file with the results.

import csv

csv_path = (r"C:\Users\ryanz\Desktop\Data Analytics Bootcamp\Resources\RICH201901DATA3\03-Python\Homework\Instructions\PyPoll\Resources\election_data.csv")

pollData = []

with open(csv_path, newline="") as csvfile:
    
    csvreader = csv.reader(csvfile, delimiter=',')
    
    csv_header = next(csvreader)
    pollData.append(csv_header)
    
    for row in csvreader:
        pollData.append(row)

# The total number of votes cast

print(f"Election Results:")
print("-----------------------------")

total_votes = 0

for row in pollData[1:]:
    total_votes += 1
print(f"Total Votes: {total_votes}")
print("-----------------------------")

# A complete list of candidates who received votes
# The percentage of votes each candidate won
# The total number of votes each candidate won

cand_list = {}
for row in pollData[1:]:
    if row[2] not in cand_list:
        cand_list[row[2]] = {}
        cand_list[row[2]]["cand_votes"] = 1
        cand_list[row[2]]["perc_votes"] = cand_list[row[2]]["cand_votes"]/total_votes
    else:
        cand_list[row[2]]["cand_votes"] += 1
        cand_list[row[2]]["perc_votes"] = cand_list[row[2]]["cand_votes"]/total_votes

for key in cand_list:
    print(key + ": " + str(format(cand_list[key]["cand_votes"])) + " (" + str(format(cand_list[key]["perc_votes"],".3%")) + ") ")


# The winner of the election based on popular vote.
most_votes = 0
winner_name = ""

for name in cand_list:
    if cand_list[name]["cand_votes"] > most_votes:
        most_votes = cand_list[name]["cand_votes"]
        winner_name = name

print("-----------------------------")     
print(f"Winner: {winner_name}"

Election Results:
-----------------------------
Total Votes: 3521001
-----------------------------
Khan: 2218231 (63.000%)
Correy: 704200 (20.000%)
Li: 492940 (14.000%)
O'Tooley: 105630 (3.000%)
-----------------------------
Winner: Khan

In [40]:
# # PyBoss - HW #3 (ExtraContent)

# In this challenge, you get to be the _boss_. You oversee hundreds of employees across the country developing Tuna 2.0, 
# a world-changing snack food based on canned tuna fish. Alas, being the boss isn't all fun, games, and self-adulation. 
#The company recently decided to purchase a new HR system, and unfortunately for you, the new system requires employee 
# records be stored completely differently.

# Your task is to help bridge the gap by creating a Python script able to convert your employee records to the required 
# format. Your script will need to do the following:

# * Import the `employee_data1.csv` and `employee_data2.csv` files, which currently holds employee records like the below:

# ```csv
# Emp ID,Name,DOB,SSN,State
# 214,Sarah Simpson,1985-12-04,282-01-8166,Florida
# 15,Samantha Lara,1993-09-08,848-80-7526,Colorado
# 411,Stacy Charles,1957-12-20,658-75-8526,Pennsylvania
# ```

# * Then convert and export the data to use the following format instead:

# ```csv
# Emp ID,First Name,Last Name,DOB,SSN,State
# 214,Sarah,Simpson,12/04/1985,***-**-8166,FL
# 15,Samantha,Lara,09/08/1993,***-**-7526,CO
# 411,Stacy,Charles,12/20/1957,***-**-8526,PA
# ```

# * In summary, the required conversions are as follows:

#   * The `Name` column should be split into separate `First Name` and `Last Name` columns.
#   * The `DOB` data should be re-written into `MM/DD/YYYY` format.
#   * The `SSN` data should be re-written such that the first five numbers are hidden from view.
#   * The `State` data should be re-written as simple two-letter abbreviations.

# * Special Hint: You may find this link to be helpful—[Python Dictionary for State Abbreviations](https://gist.github.com/afhaque/29f0f4f37463c447770517a6c17d08f5).

import csv
import datetime

# Create dynamic list
empData = []

# Define CSV path on local harddrive
csvPath = (r"C:\Users\ryanz\Desktop\Data Analytics Bootcamp\Resources\RICH201901DATA3\03-Python\Homework\ExtraContent\Instructions\PyBoss\employee_data.csv")

# Open CSV file, identify each new line with blank space at the end
with open(csvPath, newline='') as csvfile:
    
    # Define separators for each data value
    csvreader = csv.reader(csvfile, delimiter=",")
    
    # Give my data list a header and append it to the top of my list
    csv_header = next(csvreader)
    empData.append(csv_header)
    
    # for every single iteration (row) in the csv, append it to my new list
    for row in csvreader:
        empData.append(row)

# Test my list
# print(empData)
        
# # Create a list of state abbreviations based off the key value
state_abb = {
    'Alabama': 'AL',
    'Alaska': 'AK',
    'Arizona': 'AZ',
    'Arkansas': 'AR',
    'California': 'CA',
    'Colorado': 'CO',
    'Connecticut': 'CT',
    'Delaware': 'DE',
    'Florida': 'FL',
    'Georgia': 'GA',
    'Hawaii': 'HI',
    'Idaho': 'ID',
    'Illinois': 'IL',
    'Indiana': 'IN',
    'Iowa': 'IA',
    'Kansas': 'KS',
    'Kentucky': 'KY',
    'Louisiana': 'LA',
    'Maine': 'ME',
    'Maryland': 'MD',
    'Massachusetts': 'MA',
    'Michigan': 'MI',
    'Minnesota': 'MN',
    'Mississippi': 'MS',
    'Missouri': 'MO',
    'Montana': 'MT',
    'Nebraska': 'NE',
    'Nevada': 'NV',
    'New Hampshire': 'NH',
    'New Jersey': 'NJ',
    'New Mexico': 'NM',
    'New York': 'NY',
    'North Carolina': 'NC',
    'North Dakota': 'ND',
    'Ohio': 'OH',
    'Oklahoma': 'OK',
    'Oregon': 'OR',
    'Pennsylvania': 'PA',
    'Rhode Island': 'RI',
    'South Carolina': 'SC',
    'South Dakota': 'SD',
    'Tennessee': 'TN',
    'Texas': 'TX',
    'Utah': 'UT',
    'Vermont': 'VT',
    'Virginia': 'VA',
    'Washington': 'WA',
    'West Virginia': 'WV',
    'Wisconsin': 'WI',
    'Wyoming': 'WY',
}

# remove the Name element from the Employee data list and insert a First Name and Last Name Element
empData[0].remove("Name")
empData[0].insert(1, "First Name")
empData[0].insert(2, "Last Name")

# Test
# print(empData)

# Create the state abbreviation dictionary
state_list = [state_abb[x[4]] for x in empData[1:]]
# print(state_list)

# Split the name by finding the space in between of the full name 
name_list = [x[1].split(" ") for x in empData[1:]]
# print(name_list)

# Create dates with the appropriate format, as seen in row 135
#   * The `DOB` data should be re-written into `MM/DD/YYYY` format.
date_list = [(datetime.datetime.strptime(x[2], '%Y-%m-%d')).strftime('%m/%d/%Y') for x in empData[1:]] 
# print(date_list)

# Create a list within a list where the SSN is split at the "-" character
ssn_list = [x[3].split("-") for x in empData[1:]]

# # remove the old indexes for every row in the empData list
# except for the header row
for row in empData[1:]:
    row.remove(row[1])
    row.remove(row[1])
    row.remove(row[1])
    row.remove(row[1])
    
# Create a counter to be used in iterating through all of the lists created...don't grab the header row...insert new list elements
#   * The `SSN` data should be re-written such that the first five numbers are hidden from view.
counter = 0    
for row in empData[1:]:
    row.insert(1, name_list[counter][0])
    row.insert(2, name_list[counter][1])
    row.insert(3, date_list[counter])
    row.insert(4, "***-***-" + str(ssn_list[counter][2]))
    row.insert(5, state_list[counter])
    counter += 1

print("")
for row in empData:
    print(", ".join(row))
    
txt = open("EmployeeData.txt", "a")

for row in empData:
    txt.write(", ".join(row))
    txt.write("\n")
txt.close()

Emp ID, First Name, Last Name, DOB, SSN, State
232, John, Mathews, 02/24/1991, ***-***-9165, ND
533, Nathan, Moore, 11/19/1978, ***-***-7469, ME
256, Amanda, Douglas, 01/08/1990, ***-***-6961, ID
189, Heather, Andrews, 08/11/1976, ***-***-1797, VT
284, Daniel, Hernandez, 07/22/1976, ***-***-7473, CO
512, Danny, Pena, 01/31/1978, ***-***-9878, MN
126, Gary, Knight, 03/08/1994, ***-***-1242, AR
556, Robin, Carroll, 10/14/1972, ***-***-7194, CA
595, Michelle, Dickerson, 02/08/1984, ***-***-2817, TN
191, Kimberly, Gallegos, 08/05/1972, ***-***-7563, OR
55, Morgan, Parker, 01/30/1986, ***-***-4320, TN
623, Mason, Rhodes, 01/28/1977, ***-***-4767, MD
426, Amy, Griffin, 02/18/1973, ***-***-1946, MA
535, Danielle, House, 04/16/1975, ***-***-9308, ME
399, Charles, Greene, 11/28/1992, ***-***-2935, KY
33, Nicholas, Martinez, 04/05/1979, ***-***-1689, LA
302, Tracey, Meadows, 01/12/1988, ***-***-6175, RI
325, Renee, Evans, 03/14/1991, ***-***-2708, MT
188, Joseph, Estrada, 03/29/1984, ***-***-2571, PA
184, Jeremy, Warner, 10/20/1987, ***-***-1184, AL
526, Anthony, Rodriguez, 02/09/1983, ***-***-3865, ID
85, Kristen, Lopez, 01/02/1978, ***-***-8194, VA
171, Mark, Mcdonald, 06/27/1984, ***-***-0101, MT
74, Robert, Freeman, 01/01/1984, ***-***-5211, AR
69, Michael, Reynolds, 10/30/1994, ***-***-8507, CA
365, Kristine, Little, 07/10/1974, ***-***-1771, SD
149, April, Barnes, 02/15/1983, ***-***-3288, RI
218, Pamela, Hodges, 02/19/1989, ***-***-1423, UT
647, Ronald, Gilbert, 05/26/1974, ***-***-4448, WY
518, Thomas, Cooper, 08/17/1972, ***-***-9890, CO
12, Dakota, Harrington, 08/24/1972, ***-***-7188, VA
622, Jennifer, Porter, 01/20/1991, ***-***-5572, WI
159, Beverly, Jordan, 08/15/1986, ***-***-3762, NM
394, Mark, Brown, 04/02/1975, ***-***-8531, CA
158, Amy, Ford, 06/05/1974, ***-***-6461, NC
446, Benjamin, King, 05/07/1973, ***-***-8165, RI
352, Stephen, Bryant, 05/15/1991, ***-***-6488, SD
598, Brandi, Williams, 10/15/1989, ***-***-8500, MD
505, Ashley, Hutchinson, 04/26/1994, ***-***-1510, SC
173, Alisha, Pacheco, 01/13/1982, ***-***-2496, MI
84, Robert, Campbell, 02/27/1973, ***-***-9581, SD
406, Sandra, Sanders, 10/06/1980, ***-***-1673, RI
164, Katherine, Hensley, 05/29/1991, ***-***-7226, CT
267, Stacy, Cox, 11/08/1976, ***-***-0990, AL
503, Frank, Barton, 06/10/1993, ***-***-5568, MA
295, Shannon, Kramer, 05/04/1980, ***-***-7615, SC
590, Brenda, James, 12/31/1977, ***-***-3251, HI
97, Paula, Edwards, 08/10/1988, ***-***-0638, KS
3, Jennifer, Rowe, 09/16/1980, ***-***-9014, NY
20, David, Foster, 01/09/1990, ***-***-6956, MO
179, William, Boyle, 01/30/1988, ***-***-0490, AR
86, Christopher, Greene, 05/29/1972, ***-***-8446, ID
219, Matthew, Fuller, 04/27/1980, ***-***-2989, MS
237, Gabriela, Nguyen, 12/17/1981, ***-***-3729, WA
96, Allison, Diaz, 03/25/1994, ***-***-8927, AR
22, Isaac, Jordan, 05/06/1986, ***-***-0520, TX
439, Cheryl, Bailey, 10/31/1991, ***-***-1224, NC
146, Julie, Castillo, 02/16/1988, ***-***-4523, AK
271, Michael, Adams, 12/10/1986, ***-***-3927, FL
103, Melinda, Parsons, 02/07/1986, ***-***-8751, NE
540, Robert, Campbell, 01/17/1987, ***-***-3694, DE
144, Julie, Nelson, 08/08/1994, ***-***-1332, SD
594, Steven, Nelson, 04/14/1989, ***-***-2085, VT
176, Hailey, Lynn, 03/25/1973, ***-***-9488, CA
198, Dillon, Nguyen, 05/26/1978, ***-***-4552, IL
433, Hannah, Miller, 10/18/1973, ***-***-4657, NY
274, Jeffrey, Harris, 05/25/1994, ***-***-4763, KY
6, Daniel, Welch, 08/08/1982, ***-***-6950, IL
452, Bryan, Jackson, 09/08/1982, ***-***-8117, MD
23, Denise, George, 09/07/1990, ***-***-4879, WI
373, Alicia, Carney, 09/10/1989, ***-***-9437, OH
374, William, Peters, 03/20/1986, ***-***-7516, KY
200, Dustin, Drake, 09/17/1993, ***-***-5454, WV
428, Jessica, Thornton, 01/03/1983, ***-***-2381, KS
116, Rebecca, Wilson, 06/08/1980, ***-***-6629, MI
418, Katherine, Lane, 11/01/1986, ***-***-6820, NH
9, Sarah, Harper, 07/27/1993, ***-***-5891, AK
230, Jermaine, Hill, 09/11/1988, ***-***-5479, NJ
502, Michael, Marshall, 04/05/1990, ***-***-5125, MI
632, Kirsten, Mcbride, 09/10/1973, ***-***-2372, IA
112, Rachael, Holmes, 07/30/1973, ***-***-2067, GA
422, Leon, Foster, 09/19/1975, ***-***-3153, SC
131, David, Mcclain, 08/02/1976, ***-***-5430, OH
404, Emily, Lawrence, 11/24/1991, ***-***-1991, TN
504, Troy, Booth, 12/27/1990, ***-***-5141, TN
194, Stephanie, Ho, 04/25/1983, ***-***-3656, KS
567, Michele, Hendricks, 03/10/1990, ***-***-7341, MS
253, Eric, Harper, 11/12/1986, ***-***-2860, NV
407, Jonathan, Gomez, 06/05/1993, ***-***-4727, SD
82, Kevin, Garcia, 11/25/1977, ***-***-4722, NV
429, Howard, Lawson, 04/13/1984, ***-***-7664, MI
78, Stacy, Robertson, 09/24/1974, ***-***-0248, WY
167, John, Beck, 07/27/1985, ***-***-3635, AR
484, Julia, Morgan, 03/18/1976, ***-***-1731, WI
60, Allen, Leon, 04/06/1975, ***-***-9089, MI
400, James, Rios, 03/04/1978, ***-***-3987, ID
34, Ralph, Wells, 10/19/1988, ***-***-4237, KS
596, Megan, Chavez, 10/08/1991, ***-***-7659, CT
279, Ashley, Patrick, 06/07/1974, ***-***-0763, WY
466, Bonnie, Bowen, 11/07/1993, ***-***-5889, ID
327, Andrew, Lawson, 04/05/1982, ***-***-7313, MT
382, Tonya, Chavez, 04/17/1984, ***-***-5703, MT
369, Michelle, Larson, 03/20/1980, ***-***-3866, FL
347, Mark, Garrett, 09/18/1985, ***-***-4408, WY
25, Chelsea, Rivera, 06/21/1987, ***-***-0140, NH
317, Amanda, Krause, 11/06/1977, ***-***-4744, IL
321, Paige, Spencer, 09/02/1991, ***-***-8621, NY
193, Rhonda, Gonzales, 06/07/1976, ***-***-4110, ID
606, Jasmine, Kelly, 06/30/1979, ***-***-3251, MN
123, Amy, Sherman, 08/04/1973, ***-***-6029, NJ
566, David, Arroyo, 04/16/1975, ***-***-9403, FL
409, Robert, Lin, 11/12/1975, ***-***-0121, AZ
265, Paul, Wilson, 06/19/1993, ***-***-9871, IA
490, Paul, Meyers, 03/13/1989, ***-***-1680, HI
311, Jessica, Elliott, 06/04/1978, ***-***-1632, OH
537, Anthony, Richmond, 10/05/1989, ***-***-8935, AR
147, William, Rivera, 03/08/1975, ***-***-7032, SD
304, Sheri, Villegas, 02/13/1985, ***-***-8629, OR
472, Kelly, Hopkins, 10/08/1984, ***-***-6875, HI
348, Darren, Farrell, 05/24/1991, ***-***-5885, CA
91, Darlene, Harmon, 05/05/1980, ***-***-3052, WV
410, Rachel, Lyons, 08/29/1972, ***-***-0900, ME
344, David, Jacobs, 02/28/1982, ***-***-3682, FL
419, Christina, Weeks, 10/15/1972, ***-***-2028, PA
1, Andrea, Anderson, 11/12/1984, ***-***-5650, CT
532, Jennifer, Smith, 01/31/1989, ***-***-1748, GA
107, Shirley, Andrews, 12/07/1981, ***-***-5306, OH
166, Adrian, Rivera, 02/13/1973, ***-***-5638, MA
391, George, Mckinney, 02/04/1984, ***-***-7748, UT
67, Hailey, Boyd, 11/17/1980, ***-***-0270, NY
447, Tiffany, Harris, 01/12/1983, ***-***-9733, WV
653, Mary, Hunter, 11/01/1977, ***-***-6623, TX
294, Robert, Edwards, 04/07/1980, ***-***-5215, GA
416, Barbara, Lambert, 09/07/1979, ***-***-5353, ID
185, Angela, Armstrong, 03/22/1990, ***-***-2446, NY
637, Brett, Ward, 09/27/1979, ***-***-0204, MN
333, Troy, Sanchez, 11/15/1990, ***-***-2052, OK
579, Garrett, Carter, 09/26/1988, ***-***-7246, CA
215, James, Reeves, 01/31/1988, ***-***-1620, IN
152, Mary, Baker, 07/08/1979, ***-***-0954, MI
301, Alexandra, Bradley, 06/13/1980, ***-***-9390, AL
572, Aaron, James, 03/25/1974, ***-***-4596, OR
165, Thomas, Wood, 08/21/1979, ***-***-8269, TN
639, Charlene, Jackson, 10/28/1989, ***-***-8809, WY
405, Mary, Robbins, 12/01/1975, ***-***-9514, FL
390, Kayla, Washington, 10/08/1985, ***-***-6218, CT
641, Kimberly, Knapp, 11/23/1992, ***-***-1122, CO
51, Nicholas, Brown, 09/18/1988, ***-***-2869, SC
421, Rebecca, Marshall, 05/06/1974, ***-***-1020, PA
106, Mark, Smith, 07/07/1979, ***-***-5381, ND
379, Adam, Harrell, 10/18/1981, ***-***-0742, WV
76, Steve, Daniels, 09/14/1980, ***-***-3537, CO
68, Victoria, Potter, 03/25/1988, ***-***-4290, UT
118, Kathy, Preston, 03/06/1990, ***-***-9960, LA
127, Michael, Donaldson, 01/01/1995, ***-***-7624, CA
542, Brian, Bridges, 02/22/1976, ***-***-4546, MN
181, Martha, Gonzalez, 01/17/1981, ***-***-8342, KS
111, Paul, Rogers, 01/10/1992, ***-***-6284, MT
481, Dawn, Galvan, 09/03/1989, ***-***-8058, TN
568, Amber, West, 01/19/1978, ***-***-7363, ND
395, Christopher, Guerrero, 01/29/1983, ***-***-4036, WY
345, Stacy, Brooks, 06/17/1991, ***-***-4661, SC
438, Danielle, Kaiser, 08/21/1975, ***-***-9764, AL
403, Taylor, Boyle, 09/26/1979, ***-***-9756, MD
180, Donna, Howard, 12/16/1978, ***-***-3416, CA
616, Anne, Rios, 11/26/1974, ***-***-6513, HI
56, Theresa, Barnes, 09/28/1976, ***-***-2054, CT
153, Lori, Tate, 03/08/1977, ***-***-9123, NM
551, Alexandria, Baker, 11/02/1974, ***-***-3200, NV
135, Stephen, Hensley, 09/30/1978, ***-***-5372, GA
500, Jennifer, Fischer, 11/19/1983, ***-***-5609, UT
24, Pamela, Robinson, 02/21/1981, ***-***-4275, NM
81, Brendan, Gonzalez, 08/02/1991, ***-***-9993, SC
50, Richard, Turner, 12/24/1982, ***-***-9924, TN
328, Michael, Robinson, 10/22/1973, ***-***-2355, IL
402, Patricia, Sharp, 07/13/1987, ***-***-0306, MD
255, Elizabeth, Avila, 03/15/1977, ***-***-8453, NH
413, Christopher, Martinez, 12/28/1978, ***-***-8774, CT
507, Isaac, Woods, 03/20/1984, ***-***-6227, AK
62, Adriana, Wolf, 10/17/1994, ***-***-1702, OR
150, David, Pearson, 06/14/1982, ***-***-1781, AL
109, Matthew, Kramer, 05/14/1988, ***-***-4860, RI
310, Pamela, Archer, 10/25/1987, ***-***-2625, WV
243, Charles, Stout, 12/05/1976, ***-***-1997, KS
72, Daniel, Boyd, 07/18/1978, ***-***-1220, NY
608, Jimmy, Jones, 02/19/1973, ***-***-2030, MA
19, Rebecca, Hammond, 02/21/1972, ***-***-2706, LA
30, Emily, Diaz, 12/04/1986, ***-***-9174, AK
119, Chad, Wise, 11/10/1988, ***-***-1355, CO
162, Todd, Duran, 01/14/1976, ***-***-1832, KY
199, Brian, Mclaughlin, 09/21/1987, ***-***-2876, PA
187, Katherine, Rogers, 05/13/1988, ***-***-9500, ME
102, Joseph, Adams, 01/18/1979, ***-***-7778, WI
385, David, Lowery, 10/21/1987, ***-***-7963, UT
626, Janice, Young, 07/07/1988, ***-***-4863, WA
528, Anna, Matthews, 02/09/1991, ***-***-4474, TN
31, Katie, Garcia, 03/22/1983, ***-***-8462, AK
43, Maria, Estrada, 04/30/1990, ***-***-8108, LA
169, Ashley, Smith, 07/16/1983, ***-***-8720, TX
204, Amy, Wright, 10/15/1991, ***-***-8641, CA
494, Heather, Scott, 08/20/1982, ***-***-0361, NH
233, John, Anderson, 05/30/1973, ***-***-6681, NY
638, John, Anderson, 01/07/1983, ***-***-7935, UT
57, Kimberly, Harris, 10/01/1988, ***-***-5459, IA
648, Christopher, Smith, 11/23/1976, ***-***-2521, WI
192, Daniel, Singh, 12/25/1980, ***-***-7521, VA
73, Miranda, Nguyen, 08/12/1981, ***-***-2585, ME
477, Gregory, Simpson, 07/09/1990, ***-***-9365, CO
411, Daniel, Brown, 04/19/1984, ***-***-6526, NM
630, Susan, Thompson, 05/17/1985, ***-***-6074, TN
600, Rick, Johns, 07/30/1984, ***-***-7121, NV
634, Sean, Calhoun, 07/31/1978, ***-***-2261, SD
296, Alan, Holden, 11/06/1994, ***-***-6916, PA
154, Robin, Silva, 07/14/1987, ***-***-0453, AK
527, Nicole, Conrad, 06/02/1985, ***-***-6985, SD
635, Deanna, Russell, 07/29/1972, ***-***-9236, MD
229, Joshua, Bailey, 07/20/1986, ***-***-4031, WV
389, Daniel, Patrick, 10/15/1972, ***-***-8777, GA
220, William, Smith, 06/04/1990, ***-***-0654, AR
454, Kristin, Grant, 08/23/1980, ***-***-9693, WV
488, Kimberly, Velasquez, 01/10/1989, ***-***-4229, GA
41, Michael, Dalton, 03/08/1994, ***-***-2101, WI
522, Jason, Shaw, 11/01/1985, ***-***-4765, KY
269, Jonathon, Olson, 07/08/1985, ***-***-7767, SC
35, Andrea, Perry, 02/01/1986, ***-***-8897, CO
10, Anthony, Nguyen, 10/09/1986, ***-***-8472, WI
397, Anthony, Christensen, 05/13/1983, ***-***-8703, OH
45, Paul, Murphy, 07/18/1975, ***-***-9454, NJ
210, Susan, Stewart, 04/23/1989, ***-***-2712, GA
197, Scott, Warren, 06/24/1985, ***-***-3723, OH
354, Jennifer, Avery, 08/08/1987, ***-***-5062, LA
552, Alexander, Vaughan, 08/22/1988, ***-***-8562, MI
414, Laura, Parker, 12/05/1973, ***-***-6879, CO
134, Derek, Harrington, 09/15/1990, ***-***-2836, AR
11, Daniel, Wells, 08/27/1994, ***-***-7268, CA
222, Kelly, Phillips, 11/05/1987, ***-***-1324, MI
442, Lauren, Bennett, 06/05/1985, ***-***-4874, IA
633, Aaron, Wolf, 04/09/1978, ***-***-1149, WY
361, Julia, Wright, 09/04/1980, ***-***-6702, CO
205, Cheryl, Dennis, 06/16/1986, ***-***-0712, TX
18, Donna, Lopez, 02/22/1985, ***-***-5711, DE
459, Matthew, Gibbs, 06/12/1984, ***-***-9698, ID
564, Nancy, Mitchell, 02/02/1988, ***-***-9365, GA
138, Ashley, Bullock, 07/23/1983, ***-***-5394, MS
356, Andrew, Moore, 01/03/1982, ***-***-5178, ID
479, Joseph, Martinez, 10/05/1973, ***-***-9409, NH
100, Yvette, Rodriguez, 09/11/1985, ***-***-8123, OR
451, Carrie, Barber, 11/09/1977, ***-***-3083, LA
432, Ashley, Sherman, 10/01/1984, ***-***-1501, NE
71, Craig, Garcia, 08/18/1994, ***-***-3695, PA
463, Jerome, Brown, 07/10/1992, ***-***-9456, MD
308, Kevin, Beck, 03/29/1981, ***-***-7304, TN
591, Travis, Hansen, 07/28/1981, ***-***-6746, DE
214, Rodney, Cook, 12/15/1994, ***-***-6232, RI
290, Theresa, Brown, 02/20/1993, ***-***-3478, MN
8, Wayne, Mercer, 09/21/1989, ***-***-7254, MA
182, Mary, Lee, 04/12/1982, ***-***-7361, OH
534, Matthew, Martin, 07/12/1993, ***-***-7803, ID
511, Lee, Weber, 12/03/1988, ***-***-9830, CA
32, James, Wilson, 07/23/1977, ***-***-7343, OR
289, Angela, Clark, 04/20/1988, ***-***-3392, MN
643, Allen, Flynn, 07/25/1994, ***-***-7573, NH
234, Darrell, Coleman, 08/24/1992, ***-***-4198, WI
618, Patrick, Wells, 08/03/1979, ***-***-3209, MS
246, Tyler, Beck, 10/20/1986, ***-***-1385, HI
546, Michelle, Jenkins, 11/29/1977, ***-***-8254, NE
455, Scott, Miller, 09/27/1991, ***-***-3580, WY
341, Maria, Mcmillan, 09/07/1973, ***-***-3730, TX
252, Amy, Waller, 10/01/1980, ***-***-8763, MA
351, Jacob, Thomas, 03/31/1976, ***-***-8896, MS
493, Amanda, Jones, 07/31/1993, ***-***-0691, MN
599, Edward, Padilla, 10/09/1993, ***-***-5222, PA
315, Debra, Best, 02/20/1973, ***-***-3320, ND
577, Gregory, Roberts, 01/27/1986, ***-***-4496, IN
415, Suzanne, Wheeler, 05/19/1985, ***-***-2982, WI
303, Ann, Lewis, 01/14/1976, ***-***-0619, MT
478, Michelle, Peterson, 06/25/1984, ***-***-2154, MA
313, Adam, Thomas, 12/30/1982, ***-***-1297, VA
4, Donna, Owens, 09/26/1987, ***-***-6696, AL
249, Pamela, Lyons, 09/27/1972, ***-***-3318, AR
649, Victor, Lopez, 10/26/1987, ***-***-3964, NV
565, Matthew, Miller, 04/07/1979, ***-***-3517, CO
513, Kevin, Foster, 10/18/1985, ***-***-5090, WI
516, Alyssa, Stokes, 04/01/1973, ***-***-2432, OH
545, Mark, Saunders, 08/23/1973, ***-***-2640, VT
38, Michael, Chapman, 03/13/1977, ***-***-6874, OR
309, Cole, Farrell, 01/29/1993, ***-***-7973, IN
578, Michael, Estrada, 10/12/1994, ***-***-2448, OH
178, Shaun, Martinez, 12/11/1982, ***-***-5793, NC
359, Victoria, Moon, 01/06/1976, ***-***-8604, AZ
278, Brian, Peters, 05/07/1982, ***-***-3701, HI
292, Jose, Gonzalez, 06/01/1992, ***-***-9797, MD
87, John, Paul, 11/20/1973, ***-***-7180, KY
286, Stephanie, Smith, 04/26/1978, ***-***-1286, NH
221, Lisa, Wilson, 11/09/1993, ***-***-6950, AZ
524, Cody, Duran, 01/15/1973, ***-***-6706, NM
453, Ann, Johnson, 06/01/1981, ***-***-9046, NE
468, Paula, Hernandez, 10/12/1975, ***-***-2951, CA
444, Patrick, Barber, 07/21/1991, ***-***-9891, NY
350, Dennis, Alvarado, 11/27/1973, ***-***-4378, MT
462, David, Peterson, 06/27/1973, ***-***-7312, LA
66, Tina, Williams, 11/04/1987, ***-***-7775, OR
495, Bridget, Koch, 02/23/1973, ***-***-9714, WY
586, Adrian, Hernandez, 09/08/1993, ***-***-5101, NE
457, Andrea, Potter, 12/26/1983, ***-***-6384, NH
392, David, Williams, 07/07/1990, ***-***-6350, MA
202, Katherine, Wright, 05/10/1987, ***-***-3109, AR
467, Kevin, Taylor, 04/19/1979, ***-***-2293, NH
627, Latoya, Mitchell, 03/15/1991, ***-***-3607, ME
367, Tricia, Smith, 01/24/1992, ***-***-7866, CA
244, David, Miles, 11/26/1993, ***-***-2657, MI
620, Gina, Hoffman, 03/20/1990, ***-***-4213, UT
642, Tamara, Whitney, 09/21/1975, ***-***-9208, MO
427, John, Garcia, 04/14/1987, ***-***-3993, TX
539, Craig, Nunez, 06/13/1972, ***-***-6566, DE
98, Desiree, Ross, 07/07/1981, ***-***-2608, MS
324, Samantha, Ramirez, 08/11/1981, ***-***-7086, MD
589, David, Patton, 11/19/1978, ***-***-9705, PA
339, Caroline, Lopez, 08/09/1981, ***-***-1325, OK
645, Karen, Malone, 09/03/1985, ***-***-5442, CO
355, Daniel, Wright, 12/31/1989, ***-***-3803, FL
541, Brent, Miller, 01/14/1978, ***-***-9692, HI
360, Mitchell, Meyer, 08/31/1991, ***-***-7666, RI
39, Annette, Flores, 04/19/1977, ***-***-3196, NE
305, Wendy, Hendrix, 08/19/1983, ***-***-6634, WY
474, Alexis, Cross, 08/11/1983, ***-***-3694, MN
571, Jeffrey, Jones, 06/27/1981, ***-***-1822, SD
372, Jessica, Walsh, 06/01/1976, ***-***-2907, RI
559, Sherry, Henderson, 02/15/1991, ***-***-3768, FL
521, Jennifer, Johnson, 02/17/1978, ***-***-3102, OK
583, Scott, Ellison, 03/31/1977, ***-***-8653, NH
329, Denise, Baldwin, 04/06/1992, ***-***-7350, AL
201, Rebecca, James, 12/04/1980, ***-***-1514, MA
276, Sean, Gonzales, 08/11/1981, ***-***-8838, MO
592, Mary, Chavez, 04/27/1990, ***-***-2834, PA
124, Ralph, Martinez, 02/26/1980, ***-***-4024, WA
133, Thomas, Stone, 03/29/1973, ***-***-8227, DE
314, Christopher, Anderson, 07/01/1974, ***-***-1835, NC
562, Allison, Garcia, 02/08/1983, ***-***-0105, LA
125, Charles, Hall, 09/15/1982, ***-***-7617, PA
625, Lawrence, Roach, 04/03/1991, ***-***-2080, KY
312, Christopher, Dougherty, 03/29/1978, ***-***-0986, AL
90, William, Small, 08/05/1990, ***-***-0642, CO
236, Samuel, May, 03/30/1988, ***-***-0970, NJ
601, Brian, Lopez, 02/13/1990, ***-***-7558, DE
326, Amanda, Clark, 07/23/1991, ***-***-5043, MN
264, Cody, Taylor, 11/13/1978, ***-***-3700, SD
248, Sherry, Love, 03/24/1975, ***-***-8685, OR
485, Christine, Stone, 11/07/1978, ***-***-6503, KS
54, Kristy, Diaz, 03/26/1988, ***-***-1032, IA
2, Amy, Long, 07/19/1982, ***-***-7292, FL
298, Haley, Myers, 03/20/1985, ***-***-0757, MD
99, Michael, Holden, 07/23/1975, ***-***-7951, IN
186, Kelly, Ferrell, 01/21/1982, ***-***-2299, NH
593, Rachel, Valdez, 05/21/1985, ***-***-0852, UT
557, Kristine, Roberson, 03/18/1981, ***-***-0956, MN
375, Vincent, Watson, 12/15/1974, ***-***-8997, RI
460, Elizabeth, Bailey, 07/15/1979, ***-***-7230, MI
496, Mark, Mcmillan, 07/08/1976, ***-***-2503, MI
487, Sheri, Long, 06/06/1978, ***-***-5166, OH
469, Daniel, Mccall, 07/12/1987, ***-***-5314, NE
340, Dawn, Malone, 04/19/1979, ***-***-2070, TN
363, Evan, Romero, 08/25/1994, ***-***-3334, NM
108, Paul, Adams, 04/19/1992, ***-***-5765, WV
357, Tracy, Holt, 10/20/1988, ***-***-1413, AK
293, Charles, Wheeler, 02/11/1972, ***-***-5781, CA
604, Ashley, Harris, 08/09/1993, ***-***-7070, IL
7, Roberto, Schmidt, 02/07/1994, ***-***-1763, AL
94, Margaret, Barton, 10/10/1975, ***-***-0973, ID
227, Michelle, Diaz, 09/25/1993, ***-***-4889, ID
486, Mike, Duncan, 12/15/1988, ***-***-8115, MD
613, Alexandra, Thomas, 01/12/1994, ***-***-6760, SD
603, Mark, Murillo, 09/22/1976, ***-***-9915, MI
332, Carol, Dyer, 03/12/1989, ***-***-5545, HI
587, Daniel, Williams, 11/17/1989, ***-***-9146, NH
602, Sandra, Suarez, 09/20/1980, ***-***-9548, GA
398, Sarah, Hamilton, 07/20/1976, ***-***-3104, ND
148, Sydney, Floyd, 03/31/1981, ***-***-0722, CT
223, Jonathan, Hall, 07/01/1978, ***-***-6672, NE
574, Jennifer, Kim, 10/03/1976, ***-***-9504, MN
588, Kenneth, Sanchez, 10/30/1980, ***-***-8921, CA
157, Joseph, Carroll, 05/09/1975, ***-***-5984, ND
175, Jennifer, Arnold, 10/18/1976, ***-***-4368, AL
473, David, Le, 08/31/1976, ***-***-5444, MI
29, Jeffrey, Clark, 06/28/1978, ***-***-0316, MO
334, Jeffery, Reed, 07/19/1985, ***-***-6338, NJ
465, Laura, Kim, 07/26/1974, ***-***-3606, PA
92, Derek, Obrien, 06/29/1990, ***-***-6123, NH
470, Brooke, Bishop, 12/18/1980, ***-***-4107, CA
128, Peter, Miles, 10/26/1976, ***-***-3367, WA
77, Alex, Owen, 10/07/1987, ***-***-9252, AL
530, Michael, Fowler, 08/28/1990, ***-***-3995, TN
270, Katherine, Rose, 01/19/1976, ***-***-0446, MN
251, Daniel, Waller, 04/23/1974, ***-***-0011, KY
277, Ronald, Johnson, 09/19/1973, ***-***-8871, DE
346, Austin, Gutierrez, 06/25/1979, ***-***-0203, VT
238, Brandon, Chang, 05/14/1984, ***-***-6687, AL
143, Alexander, Murphy, 05/05/1984, ***-***-0664, UT
461, Stephanie, Mendoza, 03/22/1977, ***-***-8308, VT

In [ ]:
# # PyParagraph

# ![Language](Images/language.jpg)

# In this challenge, you get to play the role of chief linguist at a local learning academy. As chief linguist, you are responsible for assessing the complexity of various passages of writing, ranging from the sophomoric Twilight novel to the nauseatingly high-minded research article. Having read so many passages, you've since come up with a fairly simple set of metrics for assessing complexity.

# Your task is to create a Python script to automate the analysis of any such passage using these metrics. Your script will need to do the following:

# * Import a text file filled with a paragraph of your choosing.

# * Assess the passage for each of the following:

#   * Approximate word count

#   * Approximate sentence count

#   * Approximate letter count (per word)

#   * Average sentence length (in words)

# * As an example, this passage:

# > “Adam Wayne, the conqueror, with his face flung back and his mane like a lion's, stood with his great sword point upwards, the red raiment of his office flapping around him like the red wings of an archangel. And the King saw, he knew not how, something new and overwhelming. The great green trees and the great red robes swung together in the wind. The preposterous masquerade, born of his own mockery, towered over him and embraced the world. This was the normal, this was sanity, this was nature, and he himself, with his rationality, and his detachment and his black frock-coat, he was the exception and the accident a blot of black upon a world of crimson and gold.”

# ...would yield these results:

# ```output
# Paragraph Analysis
# -----------------
# Approximate Word Count: 122
# Approximate Sentence Count: 5
# Average Letter Count: 4.6
# Average Sentence Length: 24.0
# ```

# * **Special Hint:** You may find this code snippet helpful when determining sentence length (look into [regular expressions](https://en.wikipedia.org/wiki/Regular_expression) if interested in learning more):

# ```python
# import re
# re.split("(?<=[.!?]) +", paragraph)
# ```

# import paragraph
txtfile = open("C:/Users/sethn/Desktop/python-challenge/paragraph_1.txt")

# create lists and the necessary info about each.
Prgh = txtfile.read()
Wrds = len(Prgh.split(" "))
Sntncs = len(Prgh.split(".")) - 1

# find the number of letters
Ltrs = 0
for i in Prgh:
    if i.isalnum():
        Ltrs += 1

# find the averages
AvgLC = Ltrs / Wrds
AvgSL = Wrds / Sntncs


print("Paragraph Analysis")
print("-----------------")
print(f"Approximate Word Count: {Wrds}")
print(f"Approximate Sentence Count: {Sntncs}")
print(f"Approximate Letter Count: {round(AvgLC, 1)}")
print(f"Average Sentence Length: {round(AvgSL, 1)}")

with open("ParagraphAnalysis.txt", "a") as txt:
    txt.write("Paragraph Analysis\n")
    txt.write("-----------------\n")
    txt.write(f"Approximate Word Count: {Wrds}\n")
    txt.write(f"Approximate Sentence Count: {Sntncs}\n")
    txt.write(f"Approximate Letter Count: {round(AvgLC, 1)}\n")
    txt.write(f"Average Sentence Length: {round(AvgSL, 1)}\n")